## HW4 Numpy와 Pandas
## 201723371 강지애

## Pandas 기초연습문제

In [1]:
# pandas를 import하기
import pandas as pd

### 1.딕셔너리를 이용하여 다음과 같은 모양의 data frame 생성

In [2]:
score={'학번':[201524213,201621223,201621233, 201611111, 201722222],
       '이름':['오지환','박용택','정성훈', '다니엘', '지민'],
       '학과':['경영정보','경영정보','경영정보','컴퓨터공학','컴퓨터공학'],
       'Quiz':[15,20,10,17,18],
       '중간고사':[20,20,15,18,16]}

df= pd.DataFrame(score)
df

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
2  201621233  정성훈   경영정보    10    15
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16

In [3]:
df['학번'] ## 학번이라는 이름을 가진 컬럼의 데이터만 가져오기

0    201524213
1    201621223
2    201621233
3    201611111
4    201722222
Name: 학번, dtype: int64

### 2. 위에서 생성한 데이터프레임으로부터 인덱싱을 이용하여 이름과 중간고사를 추출하시오.

In [4]:
df[['이름', '중간고사']] ## '이름'과 '중간고사' 컬럼의 데이터만 가져오기

이름  중간고사
0  오지환    20
1  박용택    20
2  정성훈    15
3  다니엘    18
4   지민    16

### 3. reindex를 이용하여 2, 0, 4, 1, 3 순으로 순서를 변경하시오.

In [5]:
df = df.reindex([2,0,4,1,3])  # 데이터프레임에 reindex를 적용하여 원하는 순서로 변경
df

학번   이름     학과  Quiz  중간고사
2  201621233  정성훈   경영정보    10    15
0  201524213  오지환   경영정보    15    20
4  201722222   지민  컴퓨터공학    18    16
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

### 4. iloc과 loc을 각각 이용하여 박용택 학생의 record를 추출하시오. (iloc으로 한 번, loc로 한 번 수행)

In [6]:
#  iloc : 위치를 이용하여 선택하는 함수
## df에서 인덱스 번호 3 (네 번째 행)을 선택하여 추출하는 방법입니다.
print(df.iloc[3])

# loc : 라벨의 이름을 이용하여 선택
## 행의 이름이 1인 박용택을 선택하여 출력
print(df.loc[1])

학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object
학번      201621223
이름            박용택
학과           경영정보
Quiz           20
중간고사           20
Name: 1, dtype: object


### 5. iloc과 loc을 각각 이용하여 모든 학생의 이름과 중간고사 점수를 추출하시오. (iloc으로 한 번, loc으로 한 번 수행)

In [7]:
# iloc 를 활용하여 인덱스 번호 1(두 번째 열)인 열과, 인덱스 번호 4(다섯 번째 열)인 열을 추출
print(df.iloc[:, [1, 4]])

# loc 를 사용하여 열의 이름이 '이름', '중간고사' 인것을 추출
print(df.loc[:, ['이름', '중간고사']])

    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18
    이름  중간고사
2  정성훈    15
0  오지환    20
4   지민    16
1  박용택    20
3  다니엘    18


### 6. 중간고사 점수의 평균을 구하시오.

In [8]:
## mean 함수를 이용한 중간고사 행의 평균 구하기
df['중간고사'].mean()

17.8

### 7. 중간고사 점수가 가장 낮은 학생의 index를 구하시오.

In [9]:
## idxmin 함수를 이용한 중간고사 행의 min(최솟값)인 index 표시
df['중간고사'].idxmin()

2

### 8. 퀴즈 점수가 가장 높은 학생의 학번을 구하시오.

In [10]:
## idxmax 를 활용하여 Quiz 행의 점수가 max(최댓값)인 '학번' index 표시
df.loc[df['Quiz'].idxmax(), '학번']
# df.loc[df['Quiz'].idxmax()]['학번']

201621223

### 9. 위 데이터 프레임의 각 열에 대해서 개수, 평균, 표준편차, 최소최댓값 등의 다양한 통계량을 출력하시오.

In [11]:
## describe를 이용한 통계량 출력

df.describe()

학번       Quiz       중간고사
count  5.000000e+00   5.000000   5.000000
mean   2.016200e+08  16.000000  17.800000
std    7.018995e+04   3.807887   2.280351
min    2.015242e+08  10.000000  15.000000
25%    2.016111e+08  15.000000  16.000000
50%    2.016212e+08  17.000000  18.000000
75%    2.016212e+08  18.000000  20.000000
max    2.017222e+08  20.000000  20.000000

### 10. 위 데이터프레임을 중간고사 점수에 따라 내림차순으로 정렬하시오.

In [12]:
## pandas의 sort_values를 이용하여 중간고사 행의 내림차순 하기
## 내림차순 : ascending=False
## 오름차순 : ascending=True (기본적으로 오름차순으로 정렬됨)
df.sort_values('중간고사', ascending=False)

학번   이름     학과  Quiz  중간고사
0  201524213  오지환   경영정보    15    20
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18
4  201722222   지민  컴퓨터공학    18    16
2  201621233  정성훈   경영정보    10    15

### 11. 학생 중에서 퀴즈 점수가 평균 이상인 학생들의 이름을 출력하시오.

In [13]:
## mean을 이용하여, 퀴즈 점수 중 퀴즈의 평균값보다 큰 학생들의 이름을 출력

quiz_mean = df['Quiz'].mean()
df[df['Quiz'] > quiz_mean]['이름']

4     지민
1    박용택
3    다니엘
Name: 이름, dtype: object

### 12. 학생 중에서 퀴즈와 중간고사 점수 모두 평균 이상인 학생들의 record를 출력하시오.

In [14]:
## '&'를 이용하여 두 가지 조건 모두를 만족시키는 값을 출력

quiz_mean = df['Quiz'].mean() # 퀴즈의 평균값을 quiz_mean으로 저장
mid_mean = df['중간고사'].mean() # 중간고사의 평균값을 mid_mean 으로 저장
df[(df['Quiz'] > quiz_mean) & (df['중간고사'] > mid_mean)] #퀴즈 평균보다 크고, 중간고사 평균보다 큰 행을 출력

학번   이름     학과  Quiz  중간고사
1  201621223  박용택   경영정보    20    20
3  201611111  다니엘  컴퓨터공학    17    18

### 13. value_counts를 이용하여 학과 별로 학생의 수를 구하시오.

In [15]:
## value_counts를 이용하여 이름이 '학과' 인것의 value 수를 세기

df['학과'].value_counts()

경영정보     3
컴퓨터공학    2
Name: 학과, dtype: int64

### 14. groupby를 이용하여 학과 별로 중간고사의 평균을 구하시오.

In [16]:
## groupby를 통하여 '학과'의 그룹별로 나눠주고, 학과 별로 중간고사 평균을 출력

df.groupby('학과')['중간고사'].mean()

학과
경영정보     18.333333
컴퓨터공학    17.000000
Name: 중간고사, dtype: float64

In [17]:
df.mean() # 이 데이터 프레임의 평균값 출력

학번      201620000.4
Quiz           16.0
중간고사           17.8
dtype: float64

In [18]:
list(df.groupby('학과')) # 학과별로 나눈 list 출력

[('경영정보',
            학번   이름    학과  Quiz  중간고사
  2  201621233  정성훈  경영정보    10    15
  0  201524213  오지환  경영정보    15    20
  1  201621223  박용택  경영정보    20    20),
 ('컴퓨터공학',
            학번   이름     학과  Quiz  중간고사
  4  201722222   지민  컴퓨터공학    18    16
  3  201611111  다니엘  컴퓨터공학    17    18)]

## Numpy 기초연습문제

In [19]:
# numpy를 import
import numpy as np

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [20]:
## a'라는 이름의 0으로 초기화 된 행3, 열4인 다차원 배열을 생성한다.
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.

In [21]:
## a.shape[0]은 3(행), a.shape[1]은 4(열)이므로 
## i는 순서대로 0,1,2의 값을 넣어 계산되고
## j는 순서대로 0,1,2,3의 값을 넣어 계산된다.

for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [22]:
## num = 1 로 정해두고 for 문을 활용하여
## 3행 4열 동안 순서대로 1씩 더하여 다음 값을 채워준다.

num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [23]:
## 인덱스는 0부터 시작
## 2행 3열의 값을 꺼내와야 하므로 1(두 번째 행), 2(세 번째 열) 을 입력해준다.
a[1, 2]

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

In [24]:
a.shape

(3, 4)

In [25]:
## 두 번째 행을 출력하기 위하여 인덱스 1 (두 번째 행)을 입력해준다.
a[[1], :]

array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

In [26]:
## [행,열] 이기 때문에 a[,[1,2]]를 입력하여 두 번째 열(인덱스1), 세 번째 열(인덱스2)를 출력

a[:,[1, 2]]

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.

In [27]:
## np.asarry 함수 : 입력 데이터를 ndarray로 변환하나 이미 ndarray일 경우에는 새로 메모리에 ndarray가 생성되지는 않는다

result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [28]:
## a 중에서 6보다 같거나 작은 값들을 인덱싱
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.


In [29]:
## np.random.random(=np.random.rand)
## 0과 1 사이의 균일 분포에서 랜덤한 수로 matrix array 생성

b = np.random.random((3, 4))
b

array([[0.74681153, 0.13438626, 0.35389867, 0.98056209],
       [0.97309685, 0.72919949, 0.62805807, 0.9369606 ],
       [0.76591896, 0.12439229, 0.35536272, 0.71153083]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [30]:
## a*b = c

c = a * b
c

array([[0.74681153, 0.26877252, 1.06169602, 3.92224836],
       [4.86548427, 4.37519691, 4.39640652, 7.49568479],
       [6.89327063, 1.24392286, 3.90898987, 8.53836997]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [31]:
## T 속성을 통해서 2차원 배열의 전치(transpose)행과 열을 바꾸는 작업을 진행할 수 있다.

d = b.T
d

array([[0.74681153, 0.97309685, 0.76591896],
       [0.13438626, 0.72919949, 0.12439229],
       [0.35389867, 0.62805807, 0.35536272],
       [0.98056209, 0.9369606 , 0.71153083]])

In [32]:
## d의 shpae은 4행 3열로 b 행렬이 전치된 것을 볼 수 있음.

d.shape

(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [33]:
print(a.shape, d.shape)

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [34]:
## .dot을 이용하여 a와 d의 행렬곱을 실행할 수 있음

e = a.dot(d)
e

array([[ 5.99952843,  8.06351244,  4.926915  ],
       [14.86216263, 21.13277249, 12.75573416],
       [23.72479684, 34.20203254, 20.58455332]])

### 12. e에 대하여 각 열의 합을 계산하시오.

In [35]:
## .sum으로 모든 element의 합을 구할 수 있습니다.
## axis=0은 x축만을 갖는 자료형입니다. 즉 1차원 배열에 해당하는 벡터의 각 요소(Element)는 그 자체가 Row입니다.
## axis=0은 x축의 행과 y축의 컬럼(열)을 갖습니다. 2차원 배열 행렬은 depth가 1이라고 생각 할 수 있습니다.

np.sum(e, axis=0) ## axis=0 의 기준 합계

array([44.5864879 , 63.39831746, 38.26720248])

In [36]:
np.sum(e, axis=1) ## axis=1 의 기준 합계

array([18.98995587, 48.75066928, 78.5113827 ])